translation complete，PR for review
azureselected/azureselected pull request #15
Opened 2020-01-02 16:04 UTC by kongxiangyan

Manage multiple Azure tenancies with Azure Lighthouse 翻译完成，等待校验！

Fixes #13

2020-01-03 03:00 UTC, XtaoBai requested changes
疏通了部分语句，消除了部分歧义。等待进一步确认修改。

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +今年早些时候，Azure Lighthouse 在我们的合作伙伴会议（Microsoft Ready）上发布，它将 Azure 的资源管理能力带上了新的高度。您千万不要认为 Microsoft 的合作伙伴（例如托管服务提供商（MSP））是这项功能的唯一的受益者！事实上，大量企业对单独的 Azure 环境有业务需求，包括跨国公司，品牌集团和特许经营/所有者运营商业务，它们都会从中受益。最棒的是，除
```suggestion
[今年早些时候，Azure Lighthouse 在我们的合作伙伴会议（Microsoft Ready）上发布](https://azure.microsoft.com/blog/introducing-azure-lighthouse/?WT.mc_id=itopstalk-blog-socuff)，它将 Azure 的资源管理能力带上了新的高度。您千万不要认为 Microsoft 的合作伙伴（例如托管服务提供商（MSP））是这项功能的唯一的受益者！事实上，大量企业对独立的 Azure 环境有业务需求，包括跨国公司、品牌集团和特许经营/业主运营商，它们都会从中受益。最棒的是，除了像日志分析服务这样的基础计费服务外，这项新功能是完全免费的！
```
1. 补充上链接
2. 没有“所有者运营商”的说法
3. 包括应该针对企业，删除“业务”

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +我们已经在 Office 365 中见过多租户模式的运用了，它允许合作伙伴拥有客户租赁的代理访问权，用他们自己的账户登录，并通过管理面板执行任务。Azure Lighthouse 将这种模式应用到 Azure 环境中，并将它更进一步。
```suggestion
我们已经在 Office 365 中见过多租户模式的运用了，它允许合作伙伴拥有客户租赁账户的代理访问权——可以用他们自己的账户登录，并通过管理面板执行任务。Azure Lighthouse 将这种模式应用到 Azure 环境中，并将它更进一步。
```
直接说租赁的代理访问权有歧义，改为“租赁账户的代理访问权”

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +合作伙伴可以在“我的客户”面板中看到他们成功加入的所有租户的列表，包括他们在这些租户中可以访问多少个订阅或资源。这些内容也可以再细分，以准确反映合作伙伴与每个客户达成的服务协议和范围。
```suggestion
合作伙伴可以在“我的客户”面板中看到他们成功添加的所有租户的列表，并可以看到他们在这些租户中可以访问多少个订阅或资源。列表内容也可以通过进一步细分，准确反映出他们与每个客户达成的服务协议和范围。
```
列表包括有点奇怪

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +有了该访问权限，客户的 Azure 资源现在将直接显示在合作伙伴的 Azure 门户中。 这意味着合作伙伴可以在相应的 Azure 服务片区中查看所有客户的所有资源。
```suggestion
有了该访问权限，客户的 Azure 资源现在就可以直接显示在合作伙伴的 Azure 门户中。 这意味着合作伙伴可以在相应的 Azure 服务页面中查看所有客户的所有资源。
```
“就将”有点英文语言习惯风格，改为“就可以”

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +然后，合作伙伴可以通过 Azure CLI，PowerShell，HTTP Request 或 Azure 门户对这些资源执行操作。Azure 资源管理器将验证请求是否来自合作伙伴租户，然后调用托管服务资源提供程序。
```suggestion
同时，合作伙伴可以通过 Azure CLI，PowerShell，HTTP Request 或 Azure 门户对这些资源执行操作。Azure 资源管理器将验证请求是否来自合作伙伴租户，并调用托管服务资源提供程序。然后托管服务器 RP 将通过定义好的基于角色的访问控制，提供精确的访问，并根据客户的资源执行请求。
```
1. 翻译少了一句 补充上。
2. **“a partner tenant”翻译为“合作伙伴租户”** 有点奇怪，是否有其他好说法？

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +- 为您管理的所有客户定义一套标准的策略，并大规模应用 Azure 策略，包括查看哪些资源不合规。
```suggestion
- 为您管理的所有客户定义一套标准的策略，并大规模应用 Azure 策略，包括了解哪些资源不合规。
```
“查看”是一个过程词，改为“了解”

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +- 通过将自动化帐户存储在自己的合作伙伴租约中，你可以构建自动化运行手册并使用它们自动执行多个租约中的操作。同时，这些运行手册都将作为您的知识产权受到保护。
```suggestion
- 您还可以通过将自动化帐户存储在自己的合作伙伴租约中，构建出自动化运行手册，来自动执行多个租约中的操作。同时，无论是用于内部用户还是外部用户，这些运行手册都将作为您的知识产权而受到保护。
```
您放在前面通顺些

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +在客户的 Azure 门户界面中，有一个新的“服务提供商”片区。在这里，他们可以接受并批准对租约的访问，并确切规定哪些订阅或资源组可以被访问。客户还可以在 Azure 活动日志中查看其合作伙伴完整的操作历史记录。
```suggestion
在客户的 Azure 门户界面中，有一个新的“服务提供商”页面。在这里，客户可以接受并批准对租约的访问，并明确规定哪些订阅或资源组可以被访问。此外，客户还可以在 Azure 活动日志中查看其合作伙伴完整的历史操作记录。。
```
blade 翻译为页面应该比较符合意思

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +Azure Lighthouse 从委派管理访问权开始，可以通过以下两种途径完成：
```suggestion
Azure Lighthouse 委派管理访问权，可以通过以下两种途径完成：
```
从...开始有点奇怪

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +- 通过云合作伙伴门户发布公共或私有产品/服务。请注意，这里没有货币转手，与这些服务有关的任何交易均应由合作伙伴直接与客户达成。
```suggestion
- 通过云合作伙伴门户发布公共或私有服务。请注意，这里没有货币转手，任何与这些服务有关的交易均应由合作伙伴直接与客户达成。
```
/服务 感觉没有必要

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +这完全由你来决定（客户必须接受），但使用基于角色的访问控制，通常是为要执行操作的团队的贡献者开放写权限，以及为需要监视客户系统的人开放读权限。你可以通过组来管理权限和人员，客户页可以随时撤销这些权限。如果您进一步了解 RBAC，会发现这里有 70 多个内置角色及相关的访问级别供您选择或参考。
```suggestion
这完全由你来决定（客户必须接受），但使用基于角色的访问控制，通常是为要执行操作的团队的贡献者开放写权限，以及为需要监视客户系统的人开放读权限。你可以通过组来管理权限和人员，客户可以在他们的页面随时撤销这些权限。如果您进一步了解 RBAC，会发现这里有 70 多个内置角色及相关的访问级别供您选择或参考。
```
直接说客户页不明确，强调下客户

2020-01-03 03:00 UTC, XtaoBai commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
>  Azure Service Health
```suggestion
 Azure Service Health Azure 服务运行状况
```

2020-01-03 04:17 UTC, jehny2000 reviewed
(๑•̀ㅂ•́)و✧

2020-01-03 04:17 UTC, jehny2000 commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
看到了

2020-01-04 10:50 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +我们已经在 Office 365 中见过多租户模式的运用了，它允许合作伙伴拥有客户租赁的代理访问权，用他们自己的账户登录，并通过管理面板执行任务。Azure Lighthouse 将这种模式应用到 Azure 环境中，并将它更进一步。
这里确实有歧义！不过根据我的理解这里应该是指“客户租户账户中的资源”，而不是账户本身，大家觉得改成如下如何：
```suggestion
我们已经在 Office 365 中见过多租户模式的运用了，它允许合作伙伴拥有客户租户中资源的代理访问权，用他们自己的账户登录，并通过管理面板执行任务。Azure Lighthouse 将这种模式应用到 Azure 环境中，并将它更进一步。
```

2020-01-04 10:53 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +合作伙伴可以在“我的客户”面板中看到他们成功加入的所有租户的列表，包括他们在这些租户中可以访问多少个订阅或资源。这些内容也可以再细分，以准确反映合作伙伴与每个客户达成的服务协议和范围。
认可这里的改动意见！不过直译为“可以访问多少个订阅和资源”有点生硬，不妨译为“并可以看到他们在这些租户中可以访问的订阅或资源”~

2020-01-04 10:58 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +有了该访问权限，客户的 Azure 资源现在将直接显示在合作伙伴的 Azure 门户中。 这意味着合作伙伴可以在相应的 Azure 服务片区中查看所有客户的所有资源。
感谢你的斟酌！但我不同意此处改动，理由是：“将”是从一种客观的角度描述资源的显示位置的变化，如果是“就可以”，则显得客户的主动性比较强，而实际上这项功能双方都是受益者。

2020-01-04 11:26 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +然后，合作伙伴可以通过 Azure CLI，PowerShell，HTTP Request 或 Azure 门户对这些资源执行操作。Azure 资源管理器将验证请求是否来自合作伙伴租户，然后调用托管服务资源提供程序。
大意了😅 ，同征求“a parter tenant”的更好翻译！

2020-01-04 11:27 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +- 为您管理的所有客户定义一套标准的策略，并大规模应用 Azure 策略，包括查看哪些资源不合规。
接受建议！

2020-01-04 11:30 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +- 通过将自动化帐户存储在自己的合作伙伴租约中，你可以构建自动化运行手册并使用它们自动执行多个租约中的操作。同时，这些运行手册都将作为您的知识产权受到保护。
接受建议！👍

2020-01-04 11:56 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +在客户的 Azure 门户界面中，有一个新的“服务提供商”片区。在这里，他们可以接受并批准对租约的访问，并确切规定哪些订阅或资源组可以被访问。客户还可以在 Azure 活动日志中查看其合作伙伴完整的操作历史记录。
- 再次使用客户显得有点冗余，但为了表意准确！我接受建议！
- blade 实际上指的是一个导航列表项，对应的是一项功能或服务，译为页面感觉欠妥~

2020-01-04 11:57 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +Azure Lighthouse 从委派管理访问权开始，可以通过以下两种途径完成：
接受建议！

2020-01-04 11:58 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +- 通过云合作伙伴门户发布公共或私有产品/服务。请注意，这里没有货币转手，与这些服务有关的任何交易均应由合作伙伴直接与客户达成。
接受建议！

2020-01-04 11:59 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +这完全由你来决定（客户必须接受），但使用基于角色的访问控制，通常是为要执行操作的团队的贡献者开放写权限，以及为需要监视客户系统的人开放读权限。你可以通过组来管理权限和人员，客户页可以随时撤销这些权限。如果您进一步了解 RBAC，会发现这里有 70 多个内置角色及相关的访问级别供您选择或参考。
打错字啦 😑 是“客户也可以随时撤销这些权限”，感谢提醒，已修正！

2020-01-04 12:00 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
>  Azure Service Health
接受建议！

2020-01-05 10:14 UTC, shinyzhu commented
标题也需要翻译，谢谢。

2020-01-05 10:59 UTC, kongxiangyan commented
> 标题也需要翻译，谢谢。

请问需要将英文删去只留下中文吗？我一并处理！

2020-01-05 12:37 UTC, shinyzhu commented
> > 标题也需要翻译，谢谢。
> 
> 请问需要将英文删去只留下中文吗？我一并处理！

先保留原文，单独一行中文就可以。

2020-01-07 04:47 UTC, msdz commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +然后，合作伙伴可以通过 Azure CLI，PowerShell，HTTP Request 或 Azure 门户对这些资源执行操作。Azure 资源管理器将验证请求是否来自合作伙伴租户，然后调用托管服务资源提供程序。
Azure 资源管理器将验证请求是否来自一个微软合作伙伴的租户，然后再调用托管服务资源提供程序。托管服务资源提供程序通过定义的：基于角色的访问控制，提供精确的访问，并且该请求将根据客户的资源进行处理。

2020-01-07 04:50 UTC, msdz commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +*What access is needed to the customer’s tenancy?*  *客户的租约需要什么访问权限？*
*在客户的租户上需要什么访问权限？*

2020-01-07 04:59 UTC, msdz commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +这完全由你来决定（客户必须接受），但使用基于角色的访问控制，通常是为要执行操作的团队的贡献者开放写权限，以及为需要监视客户系统的人开放读权限。你可以通过组来管理权限和人员，客户页可以随时撤销这些权限。如果您进一步了解 RBAC，会发现这里有 70 多个内置角色及相关的访问级别供您选择或参考。
这完全由你来决定（客户必须接受），但使用基于角色的访问控制，通常是为要执行操作的团队赋予**参与者**的角色，以及为需要监视客户系统的人赋予**读者**的角色。你可以通过组来管理权限和人员，客户可以在他们的门户上随时撤销这些权限。如果您进一步了解 RBAC，会发现这里有 70 多个内置角色及相关的访问级别供您选择或参考。

2020-01-08 10:48 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +*What access is needed to the customer’s tenancy?*  *客户的租约需要什么访问权限？*
感谢！接受建议！

2020-01-08 10:52 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +这完全由你来决定（客户必须接受），但使用基于角色的访问控制，通常是为要执行操作的团队的贡献者开放写权限，以及为需要监视客户系统的人开放读权限。你可以通过组来管理权限和人员，客户页可以随时撤销这些权限。如果您进一步了解 RBAC，会发现这里有 70 多个内置角色及相关的访问级别供您选择或参考。
感谢！已查阅相关文档，接受“参与者”和“读者”的建议！其它部分仍按照最新版本的翻译保持不变！

2020-01-08 10:56 UTC, kongxiangyan commented on content/cloud-advocate/Manage-multiple-Azure-tenancies-with-Azure-Lighthouse.md
> +然后，合作伙伴可以通过 Azure CLI，PowerShell，HTTP Request 或 Azure 门户对这些资源执行操作。Azure 资源管理器将验证请求是否来自合作伙伴租户，然后调用托管服务资源提供程序。
感谢建议！在最新版的翻译中此处已经修订为“该程序将按照预定义的基于角色的访问控制提供精确的访问，然后，请求的操作会在客户的资源上被执行。”以符合中文的表述方式~

2020-01-22 05:22 UTC, merged